imx: add preliminary i.MX8MQ support for SolidRun boards
Add imx8mq_hb support which is the first i.MX8MQ based board
from SolidRun.  This commit is based on the support that has
already or been merged upstream, including the soon to be merged
lpddr4 initialization code.

U-Boot SPL 2018.11-00058-g517ec4c76c (Nov 28 2018 - 20:01:44 +0100)
PMIC:  PFUZE100 ID=0x10
Normal Boot
Trying to boot from MMC2
NOTICE:  Configureing TZASC380
NOTICE:  BL31: v1.6(release):v1.6-110-gb86481c5
NOTICE:  BL31: Built : 09:03:59, Sep 30 2018
NOTICE:  sip svc init

U-Boot 2018.11-00058-g517ec4c76c (Nov 28 2018 - 20:01:44 +0100)

CPU:   Freescale i.MX8MQ rev2.0 at 1000 MHz
Reset cause: POR
Model: SolidRun i.MX8MQ HummingBoard Pulse
DRAM:  3 GiB
MMC:   FSL_SDHC: 0, FSL_SDHC: 1
Loading Environment from MMC... OK
In:    serial
Out:   serial
Err:   serial
Net:
Error: ethernet@30be0000 address not set.

Signed-off-by: Jon Nettleton <jon@solid-run.com>