mvebu: bubt: always define CONFIG_MVEBU_UBOOT_DFLT_NAME
Commit 2fde99bd69e5 (mvebu: bubt: Key default bubt image rom based on
selected boot device) made CONFIG_MVEBU_UBOOT_DFLT_NAME depend on
CONFIG_ENV_IS_ON_SELECTED_BOOT_DEVICE. This breaks the build when
CONFIG_ENV_IS_ON_SELECTED_BOOT_DEVICE is not defined:

cmd/mvebu/bubt.c: In function ‘do_bubt_cmd’:
cmd/mvebu/bubt.c:944:10: error: ‘CONFIG_MVEBU_UBOOT_DFLT_NAME’ undeclared (first use in this function); did you mean ‘CONFIG_SMBIOS_PRODUCT_NAME’?
          CONFIG_MVEBU_UBOOT_DFLT_NAME,
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~

clearfog_defconfig does not define
CONFIG_ENV_IS_ON_SELECTED_BOOT_DEVICE, so this config is currently
broken.

Remove the dependency to make sure CONFIG_MVEBU_UBOOT_DFLT_NAME is
always defined.

Signed-off-by: Baruch Siach <baruch@tkos.co.il>